### ISSUE TITLE
Add ignore rules for Ableton's export windows

### ISSUE THREAD

**Issue by sisi-sh** [LGUG2Z/komorebi-application-specific-configuration#163]
## Justification
Because they are floating windows that don't really benefit from being tiled.

## Preview
From this 

![Image](https://github.com/user-attachments/assets/6f436376-bbc0-496a-90d9-07034e68d9be)

To this 

![Image](https://github.com/user-attachments/assets/d083463d-5588-4dac-91b5-d3299b3ef7d7)

## Code 

JSON

```json
  "Ableton Live": {
    "ignore": [
      ...
      {
        "kind": "Title",
        "id": "Export Audio...",
        "matching_strategy": "Equals"
      },
      {
        "kind": "Title",
        "id": "Export Audio/Video",
        "matching_strategy": "Equals"
      }
    ]
  },
```

YAML

```yaml
- name: Ableton Live
  identifier:
    kind: Class
    id: Ableton Live Window Class
    matching_strategy: Legacy
  ignore_identifiers:
  ...
  - kind: Title
    id: Export Audio/Video
    matching_strategy: Equals
  - kind: Title
    id: Export Audio...
    matching_strategy: Equals
```

---

## Bonus

Can't target Ableton's settings window because it's title is "Settings" and that has conflicts, and I don't believe there is currently a way to target specific windows of an application. Still learning komorebi, so I don't exactly understand how the "tray_and_multi_window_applications" entry works. Definitely not a big issue for now ¯\\\_(ツ)\_/¯ 

And thanks, this software is awesome
