### ISSUE TITLE
Exclude some dialog windows for Fork.exe

### ISSUE THREAD

**Issue by Stephanvs** [LGUG2Z/komorebi-application-specific-configuration#98]
Hi there!

Foremost, thanks for the great Komorebi program, I just started using it and already very happy with it.

I've observed that the Git GUI program I use, Fork, displays dialog windows for certain actions. Ideally, these should be floating and not integrated into the tiling layout. I attempted to add the necessary configurations to the application.yaml file and refreshed my settings, but it appears to have had no effect.

```yaml
- name: Fork
  identifier:
    kind: Exe
    id: Fork.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Title
    id: Discard changes
    matching_strategy: Equals
```

Here's some more diagnostic information:
```
 [➜] ~
 ››› komorebic visible-windows
{
  "GSM5B09-5&9248f87&0&UID41217": [
    {
      "title": "Fork - Repo Two",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;cd995b6c-b015-4567-9f91-cf5e1358b52e]"
    },
    {
      "title": "Discard changes",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;08d51df5-38e9-43c9-b518-1d78d3ec6f6b]"
    },
    {
      "title": "pwsh :: steph",
      "exe": "WindowsTerminal.exe",
      "class": "CASCADIA_HOSTING_WINDOW_CLASS"
    }
  ]
}
 [➜]  ~
 ››› komorebic visible-windows
{
  "GSM5B09-5&9248f87&0&UID41217": [
    {
      "title": "Fork - Repo One",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;cd995b6c-b015-4567-9f91-cf5e1358b52e]"
    },
    {
      "title": "Discard changes",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;95be9771-b71a-4833-bc63-08810074054e]"
    },
    {
      "title": "pwsh :: steph",
      "exe": "WindowsTerminal.exe",
      "class": "CASCADIA_HOSTING_WINDOW_CLASS"
    }
  ]
}
 [➜]  ~
 ››› komorebic visible-windows
{
  "GSM5B09-5&9248f87&0&UID41217": [
    {
      "title": "Fork - ProSim",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;cd995b6c-b015-4567-9f91-cf5e1358b52e]"
    },
    {
      "title": "Push",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;347e4936-5c79-4c43-bb10-c623bed45f16]"
    },
    {
      "title": "pwsh :: steph",
      "exe": "WindowsTerminal.exe",
      "class": "CASCADIA_HOSTING_WINDOW_CLASS"
    }
  ]
}
```

So there are a couple dialog windows that I'd like to show as floating, which are these:

```json
    {
      "title": "Discard changes",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;95be9771-b71a-4833-bc63-08810074054e]"
    },
```
and
```json
    {
      "title": "Push",
      "exe": "Fork.exe",
      "class": "HwndWrapper[Fork.exe;;347e4936-5c79-4c43-bb10-c623bed45f16]"
    },
```

Could you help me configure these, and I'd be happy to help debugging and providing a PR eventually.

## Version info
```
komorebic 0.1.28
tag:v0.1.28
commit_hash:0cdce8fc
build_time:2024-07-15 16:06:31 +00:00
build_env:rustc 1.79.0 (129f3b996 2024-06-10),stable-x86_64-pc-windows-msvc
```

**Comment by CAESIUS-TIM** [comment]
I'm new, too. Maybe it can work. I don't have `Fork.exe`, but at least `komorebi` doesn't report any errors or warnings.

```yaml
- name: Fork
  identifier:
    kind: Exe
    id: Fork.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Title
    id: Discard changes
    matching_strategy: Equals
  - kind: Title
    id: Push
    matching_strategy: Equals
```

This is a simple case, as long as the two title names ("Discard changes" and "Push") match exactly.

You can learn more from [doc](https://komorebi.lgug2z.com/schema#float_rules).

matching_strategy:
- "Legacy"
- "Equals"
- "StartsWith"
- "EndsWith"
- "Contains"
- "Regex"
- "DoesNotEndWith"
- "DoesNotStartWith"
- "DoesNotEqual"
- "DoesNotContain"

**Comment by andreizhvaleuski** [comment]
I had the same issue with Visual Studio.  It creates some hidden window and what I want is to make this hidden window as floating one, so it does not take a rectangle inside a layout. I made the following update to the config and run `komorebic reload-configuration` command which didn't update global state properly (check it via `komorebic global-state`), there were no rule for id WindowsFormsParkingWindow inside `float_identifiers` . 

```yaml
- name: Visual Studio
  identifier:
      kind: Exe
      id: devenv.exe
      matching_strategy: Equals
  options:
      - tray_and_multi_window
  float_identifiers:
      - kind: Title
        id: WindowsFormsParkingWindow
        matching_strategy: Equals
```

The solution was to stop and then start the komorebi again.
```pwsh
komorebic stop --whkd; komorebic start --whkd
```

After running the above command, the komorebi global state was properly updated and floating window rule appeared inside the global state.
